baseURL: https://docs.ausweisapp2.computingoverload.de/
defaultContentLanguageInSubdir: true
languageCode: en
title: ausweisapp2 documentation
DefaultContentLanguage: en
preserveTaxonomyNames: true
disableKinds:
  - taxonomyTerm

languages:
  en:
    weight: 2
    menu:
      main:
        - identifier: technical
          name: Technical documentation
          url: /en/technical
          weight: -930
  de:
    weight: 2
    menu:
      main:
        - identifier: technical
          name: Technische Dokumentation
          url: /de/technical
          weight: -930

theme: "ausweisapp2-hugo-theme"

privacy:
  disqus:
    disable: false
  googleAnalytics:
    anonymizeIP: false
    disable: false
    respectDoNotTrack: false
    useSessionStorage: false
  instagram:
    disable: false
    simple: false
  twitter:
    disable: false
    enableDNT: false
    simple: false
  vimeo:
    disable: false
    simple: false
  youtube:
    disable: false
    privacyEnhanced: false