baseURL: https://docs.ausweisapp2.computingoverload.de/
defaultContentLanguageInSubdir: true
languageCode: de
title: ausweisapp2 documentation
DefaultContentLanguage: de
preserveTaxonomyNames: true
disableKinds:
  - taxonomyTerm

languages:
  de:
    weight: 2

theme: "ausweisapp2-hugo-theme"

privacy:
  disqus:
    disable: false
  googleAnalytics:
    anonymizeIP: false
    disable: false
    respectDoNotTrack: false
    useSessionStorage: false
  instagram:
    disable: false
    simple: false
  twitter:
    disable: false
    enableDNT: false
    simple: false
  vimeo:
    disable: false
    simple: false
  youtube:
    disable: false
    privacyEnhanced: false