baseURL: http://docs.computingoverload.de/
defaultContentLanguageInSubdir: true
languageCode: en
title: easydb documentation
DefaultContentLanguage: en
preserveTaxonomyNames: true
disableKinds:
  - taxonomyTerm

languages:
  de:
    weight: 2

    menu:
      main:
        - identifier: techdocs
          name: Technische Dokumentation (EN)
          url: /en/technical
          weight: -930

  en:
    weight: 2

  zulu:
    contentDir: intern
    weight: 2

theme: "ausweisapp2-hugo-theme"
# sectionPagesMenu = "main"

pygmentsCodeFences: true

pygmentsOptions: ""
# Use the Chroma stylesheet
pygmentsUseClasses: true
pygmentsUseClassic: false

# See https://help.farbox.com/pygments.html
pygmentsStyle: "github"