name: deployment

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH Agent
        shell: bash
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
          Hostname: ${{ secrets.DEPLOYMENT_HOST }}
          PrivateKey: ${{ secrets.SSH_PRIVATE_KEY }} 
        run: |
          mkdir -p ~/.ssh
          ssh-keygen -R $Hostname >> ~/.ssh/known_hosts
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "$PrivateKey"

      - name: deploy website
        shell: bash
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
          Username: ${{ secrets.DEPLOYMENT_HOST_USER }}
          Hostname: ${{ secrets.DEPLOYMENT_HOST }}
          Port: ${{ secrets.DEPLOYMENT_HOST_PORT }}
        run: ssh $Username@$Hostname -p $Port
